name: sequential_flow
description: "A Flutter library for building declarative, step-by-step flows with comprehensive state management and customizable navigation behavior."
version: 1.1.0
homepage: https://github.com/JhonaCodes/sequential_flow

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: